### ISSUE TITLE
compatibility with EasyRSS

### ISSUE THREAD

**Issue by oupala** [plopoyop/freshrss_ynh#7]
As FreshRSS has a GoogleReader-compliant API, it is natively compatible with many RSS readers.

Among these, [EasyRSS](https://f-droid.org/repository/browse/?fdfilter=easyrss&fdid=org.freshrss.easyrss) is an opensource android client that is available on [F-Droid](https://f-droid.org/).

EasyRSS is working very well with FreshRSS as long as FreshRSS has some technical requirements met. See [this comment](https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133) for more informations.

These requirements are :

- PHP 5.4+
- PHP used as module instead of CGI (or turn on Apache mod_rewrite)
- [PHP GMP](http://php.net/gmp) extension

Could make the install script check that these requirements are met ?

**Comment by plopoyop** [comment]
Hi,
I just finish testing, I had no problem to use easyrss. After checking the documentation, I realise, it's only because my server is in x86_64.

I had the install of php gmp extension into the install script and into the upgrade script. So, it should work for everyone now.

The connection url for easy rss is :
https://yourdomain.ext/rss/api/greader.php
You have to setup an api password into your user profile since the api can't use your yunohost password.

**Comment by oupala** [comment]
Great news !

**Comment by olho** [comment]
thank you very much!!works great now the api!

**Comment by M5oul** [comment]
That should be documented on the Readme.
